site_name: Technical notes
site_url: sjpp.github.io/notes
site_description: Random bunch of technical notes and various tips
repo_name: "Gitea"
repo_url: https://github.com/sjpp/notes
use_directory_urls: true

markdown_extensions:
  - admonition
  - codehilite
  - fenced_code
  - footnotes
  - meta
  - nl2br
  - smarty
  - tables
  - toc
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.details

theme:
    name: material
    highlightjs: true
    font: false
    palette:
      primary: 'blue grey'
      accent: 'indigo'
    feature:
      tabs: false
